#!/usr/bin/env python3

import asyncio
from room import room
from story import story, story2

if __name__ == "__main__":
    g = story2.Greeter.start()
    g.tell("yo")
    # asyncio.run(story.storytime())
    # initial_lines = room.setup()
    # room.chat(initial_lines)
