#!/usr/bin/env python3

import logging
from room import room
from story import story
from listen import listen

if __name__ == "__main__":
    logging.basicConfig(level=logging.WARN)
    logging.getLogger('pykka').setLevel(logging.INFO)
    # listen.run()
    story.run()
    # initial_lines = room.setup()
    # room.chat(initial_lines)
